# **LECTURE 1 Introduction**




*   open source deeplearning framework
*   developed by facebook ai research lab





# **Tensor**

pytorch array


*   1d - line

*   2d - squere

*   3d - cube


# Tensor vs Numpy Array

tensor can run on cpu and gpu
but numpy array only run on cpu




**Installation**

cuda is gpu it's create running enviorment for pytorch with gpu



create separate ENV

*  py -3.xx -m venv myvenv
*  myvenv/Scripts/activate



In [1]:
!pip install torch

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21

In [2]:
import torch

torch.__version__

'2.3.0+cu121'

In [2]:
import numpy as np
import torch
import math
import time



In [5]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [6]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4185, 0.1374],
        [0.2594, 0.1202]]) 



In [7]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1827, 0.8984, 0.4015],
        [0.9431, 0.2746, 0.6879]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [9]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [11]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [12]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [13]:
# Set the size of the matrices
matrix_size = 1000

# NumPy Example (on CPU)
start_time_np = time.time()

# Create two random matrices
numpy_matrix1 = np.random.rand(matrix_size, matrix_size)
numpy_matrix2 = np.random.rand(matrix_size, matrix_size)

# Perform matrix multiplication
numpy_result = np.dot(numpy_matrix1, numpy_matrix2)

end_time_np = time.time()
numpy_processing_time = end_time_np - start_time_np

print(f"NumPy processing time: {numpy_processing_time:.6f} seconds")

NumPy processing time: 0.211506 seconds


In [14]:
# PyTorch Example (on CPU, if available)
start_time_torch = time.time()
matrix_size = 1000
# Create two random tensors
torch_tensor1 = torch.rand(matrix_size, matrix_size)
torch_tensor2 = torch.rand(matrix_size, matrix_size)

# Move tensors to CPU if available
if torch.cuda.is_available():
    torch_tensor1 = torch_tensor1.cuda()
    torch_tensor2 = torch_tensor2.cuda()

# Perform matrix multiplication
torch_result = torch.mm(torch_tensor1, torch_tensor2)

end_time_torch = time.time()
torch_processing_time = end_time_torch - start_time_torch

# Print processing times

print(f"PyTorch processing time: {torch_processing_time:.6f} seconds")

PyTorch processing time: 0.149309 seconds


In [6]:
# Set the size of the matrices
matrix_size = 1000

# NumPy Example (on GPU)
start_time_np = time.time()

# Create two random matrices
numpy_matrix1 = np.random.rand(matrix_size, matrix_size)
numpy_matrix2 = np.random.rand(matrix_size, matrix_size)

# Perform matrix multiplication
numpy_result = np.dot(numpy_matrix1, numpy_matrix2)

end_time_np = time.time()
numpy_processing_time = end_time_np - start_time_np

print(f"NumPy processing time: {numpy_processing_time:.6f} seconds")

NumPy processing time: 0.075468 seconds


In [5]:
# PyTorch Example (on GPU, if available)
start_time_torch = time.time()
matrix_size = 1000
# Create two random tensors
torch_tensor1 = torch.rand(matrix_size, matrix_size)
torch_tensor2 = torch.rand(matrix_size, matrix_size)

# Move tensors to GPU if available
if torch.cuda.is_available():
    torch_tensor1 = torch_tensor1.cuda()
    torch_tensor2 = torch_tensor2.cuda()

# Perform matrix multiplication
torch_result = torch.mm(torch_tensor1, torch_tensor2)

end_time_torch = time.time()
torch_processing_time = end_time_torch - start_time_torch

# Print processing times

print(f"PyTorch processing time: {torch_processing_time:.6f} seconds")

PyTorch processing time: 0.020652 seconds
